### ISSUE TITLE
Traning result : eyes don't blinking

### ISSUE THREAD

**Issue by merif** [ashawkey/RAD-NeRF#15]
![ngp_ep0028](https://user-images.githubusercontent.com/59863410/215034560-71f8e18b-dfb5-4b6b-8cf5-9dbfbf67cc07.gif)

The image above is the result of completing general learning and fine tuning. In addition, we learned by adding the --fix_eye0.25 option by referring to other issues, but the results are as above.

I think it's similar that I've learned not only from the obama video but also from other videos, but result's eyes don't blink. 
In addition to adding the --fix_eye0.25 method, I'm asking how I can learn to blink.

**Comment by ashawkey** [comment]
@merif Hi, `--fix_eye 0.25` means fixing the eye area to 0.25, so we can avoid all eye blinking. If you want to let the eye blink, you should not use this option.

**Comment by merif** [comment]
Thank you for your kind and quick reply!
