### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by chivalrousS** [ashawkey/RAD-NeRF#3]
hello, when i run the  "Pre-processing Custom Training Video" ，and run a specific step 8,  use the  script  data_utils/face_tracking/face_tracker.py  to  generate the  "track_params.pt" ,  encountered such an error:
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/6442126/206343000-a94c4fff-df93-4f62-85bf-e81d4b5c0f56.png">

thank you.

**Comment by tylersky1993** [comment]
Maybe this will help you!

[](https://github.com/YudongGuo/AD-NeRF/issues/58)
