### ISSUE TITLE
Audio FPS？

### ISSUE THREAD

**Issue by Gpwner** [ashawkey/RAD-NeRF#32]
Great Job!

这里的Audio FPS是指训练视频的FPS吗？
https://github.com/ashawkey/RAD-NeRF/blob/main/nerf/asr.py#L401
我看您在调用asr.py的时候，没有传入FPS，而代码里默认的FPS=50：
https://github.com/ashawkey/RAD-NeRF/blob/main/nerf/asr.py#L44
![image](https://user-images.githubusercontent.com/19349207/223983454-9df3c827-45d3-41d1-a99a-c38ee71eb98d.png)

**Comment by ashawkey** [comment]
@Gpwner No, the video is assumed to be 25FPS, and we always use 2 audio frames (chunks) per video frame, and that's the meaning for 50.

**Comment by Gpwner** [comment]
thanks for reply
