### ISSUE TITLE
What's new in Grid Encoder?

### ISSUE THREAD

**Issue by yerfor** [ashawkey/RAD-NeRF#33]
Thanks for your brilliant work!

I'm interested in the modifications in the latest commit that update the grid encoder, which seems to replace the `tilegrid` to `hashgrid`, Can you briefly explain what's the motivation and how you achieve it?

Sincerely.

**Comment by yerfor** [comment]
I just ablated the modifications, and it seems that the additional `.float()` in ambient net contributes significantly to the HEAD_PSNR. By contrast, the grid_type or interpolation_type have no obvious improvements.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/48365204/224200388-4c0c6dc9-26f1-43c7-8fb7-5516eaf04353.png">

**Comment by ashawkey** [comment]
@yerfor Hi, it's just an updation to keep the code consistent with other projects, and also bug fixing for gridencoder. Thanks for the ablation!

**Comment by yerfor** [comment]
Thanks a lot. Your implementation of Encoders and RayMarching in CUDA is high-efficient and elegant. May I use your implementation in my project [GeneFace(https://github.com/yerfor/GeneFace/), to replace the vanilla NeRF implementation?

**Comment by ashawkey** [comment]
Of course!

**Comment by yerfor** [comment]
thx!
