### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Gpwner** [ashawkey/RAD-NeRF#37]
I will suffer from the type error until I remove the last param ‘interpolation’
![image](https://user-images.githubusercontent.com/19349207/224590516-b6423b76-d6fa-4577-87b9-d3a1c1fbfc54.png)

please have a look at this,thanks.

**Comment by ashawkey** [comment]
@Gpwner Hi, you need to reinstall gridencoder, as we have updated it.

**Comment by Gpwner** [comment]
what you mean is re-clone the latest code from github ，right? Yes , I have done it...
![image](https://user-images.githubusercontent.com/19349207/224601602-b92a2277-e8e7-49bf-9d4e-94abc706c596.png)

Can not figure out what is wrong.

**Comment by ashawkey** [comment]
No, you need to reinstall with `pip install ./gridencoder`.
