### ISSUE TITLE
Function of Individual codes

### ISSUE THREAD

**Issue by sora158** [ashawkey/RAD-NeRF#40]
I find network has a input c, and it refers to individual codes. However , I can't find individual code in your paper. Can you explain what's the meaning of this input? Thank you!

**Comment by sora158** [comment]
In nerf/render.py,  Line `199`     

       if self.individual_dim > 0:
            if self.training:
                ind_code = self.individual_codes[index]
            # use a fixed ind code for the unknown test data.
            else:
                ind_code = self.individual_codes[0]
        else:
            ind_code = None

**Comment by yerfor** [comment]
I suppose it might be a common practice in the field of dynamic NeRF to improve image fidelity (PSNR, etc). But it seems no significant improvement in this case though.

**Comment by sora158** [comment]
Thanks for replying! I'm new to Dynamic nerf ^^. Also, I follow up your research of Geneface, your demo which uses DiffSinger looks wonderful!

**Comment by sora158** [comment]
> I suppose it might be a common practice in the field of dynamic NeRF to improve image fidelity (PSNR, etc). But it seems no significant improvement in this case though.

Thanks for replying! I'm new to Dynamic nerf ^^. Also, I follow up your research of Geneface, your demo which uses DiffSinger looks wonderful!

**Comment by yerfor** [comment]
Thanks~
