### ISSUE TITLE
使用gui界面时出现’Segmentation fault‘

### ISSUE THREAD

**Issue by begins233** [ashawkey/RAD-NeRF#8]
开发环境;WSL2 Ubuntu18.04 torch1.12 cuda 11.6
问题描述：基于VcXsrv可以正常使用dearpygui，使用本工程的界面时，出现Segmentation fault。
排除发现只要import 四个extension的库freqencoder,shencoder,gridencoder,raymarching中任意一个就会出现段错误。直接运行无界面版本程序可以成功运行。

**Comment by ashawkey** [comment]
@begins233 Sorry that the codebase is not tested on WSL2, I'm not sure about the reason.
